config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'search/search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  # get 'events/new_event_invitations', to: "event_invitations#new", as: :send_invite_otf

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        resources :mail_boxes do
          resources :inbox_messages
        end
        resources :subscriptions
      end
      resources :events do
        resources :comments
        resources :date_options do
          resources :vote_dates
        end
        resources :event_files
        resources :notifications
      end
      resources :event_invitations do
        resources :vote_dates
      end
      resources :comments
      resources :reports
      resources :organizations do
        resources :organization_files
        resources :subscriptions
      end
      resources :subscriptions
    end
  end


  resources :users, defaults: { format: :html } do
    resources :mail_boxes, defaults: { format: :html} do
      resources :inbox_messages, defaults: { format: :html}
    end
    resources :subscriptions, defaults: { format: :html }
  end
  resources :events, defaults: { format: :html } do
    resources :comments, defaults: { format: :html }
    resources :date_options, defaults: { format: :html } do
      resources :vote_dates, defaults: { format: :html }
    end
    resources :event_files, defaults: { format: :html }
    resources :notifications, defaults: { format: :html }
    resources :event_invitations, defaults: { format: :html}
  end

  resources :event_invitations, defaults: { format: :html} do
    resources :vote_dates, defaults: { format: :html }
  end
  resources :comments, defaults: { format: :html }
  resources :reports, defaults: { format: :html}
  resources :organizations, defaults: { format: :html } do
    resources :organization_files, defaults: { format: :html }
    resources :subscriptions, defaults: { format: :html }
  end
  resources :subscriptions, defaults: { format: :html }
  resources :inbox_messages, defaults: { format: :html}

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/controllers/api/v1/subscriptions_controller.rb
class API::V1::SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subscription_params
    params.fetch(:subscription, {})
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , :except => [:index,:show]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @org = Organization.all
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @org = Organization.find(params[:subscription][:organization_id])
    @subscription = @org.subscriptions.build(subscription_params)


    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @org, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.fetch(:subscription, {}).permit(:user_id, :organization_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :user %>
    <%= form.collection_select(:user_id, User.all.where(id: current_user.id), :id, :name, {}, { class: "form-control" }) %>
  </div>

  <div class="form-group">
    <%= form.label :organization %>
    <%= form.collection_select(:organization_id, Organization.all.where(:id => params[:organization_id] ), :id, :name, {}, { class: "form-control" }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>Become a member now</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', :back%>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>