config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'search/search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  # get 'events/new_event_invitations', to: "event_invitations#new", as: :send_invite_otf

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        resources :mail_boxes do
          resources :inbox_messages
        end
        resources :subscriptions
      end
      resources :events do
        resources :comments
        resources :date_options do
          resources :vote_dates
        end
        resources :event_files
        resources :notifications
      end
      resources :event_invitations do
        resources :vote_dates
      end
      resources :comments
      resources :reports
      resources :organizations do
        resources :organization_files
        resources :subscriptions
      end
      resources :subscriptions
    end
  end


  resources :users, defaults: { format: :html } do
    resources :mail_boxes, defaults: { format: :html} do
      resources :inbox_messages, defaults: { format: :html}
    end
    resources :subscriptions, defaults: { format: :html }
  end
  resources :events, defaults: { format: :html } do
    resources :comments, defaults: { format: :html }
    resources :date_options, defaults: { format: :html } do
      resources :vote_dates, defaults: { format: :html }
    end
    resources :event_files, defaults: { format: :html }
    resources :notifications, defaults: { format: :html }
    resources :event_invitations, defaults: { format: :html}
  end

  resources :event_invitations, defaults: { format: :html} do
    resources :vote_dates, defaults: { format: :html }
  end
  resources :comments, defaults: { format: :html }
  resources :reports, defaults: { format: :html}
  resources :organizations, defaults: { format: :html } do
    resources :organization_files, defaults: { format: :html }
    resources :subscriptions, defaults: { format: :html }
  end
  resources :subscriptions, defaults: { format: :html }
  resources :inbox_messages, defaults: { format: :html}

end

app/models/mail_box.rb
class MailBox < ApplicationRecord
  belongs_to :user
  has_many  :inbox_messages
end

app/controllers/api/v1/mail_boxes_controller.rb
class API::V1::MailBoxesController < ApplicationController
  before_action :set_mail_box, only: [:show, :edit, :update, :destroy]

  # GET /mail_boxes
  # GET /mail_boxes.json
  def index
    @mail_boxes = MailBox.all
  end

  # GET /mail_boxes/1
  # GET /mail_boxes/1.json
  def show
  end

  # GET /mail_boxes/new
  def new
    @mail_box = MailBox.new
  end

  # GET /mail_boxes/1/edit
  def edit
  end

  # POST /mail_boxes
  # POST /mail_boxes.json
  def create
    @mail_box = MailBox.new(mail_box_params)

    respond_to do |format|
      if @mail_box.save
        format.html { redirect_to @mail_box, notice: 'Mail box was successfully created.' }
        format.json { render :show, status: :created, location: @mail_box }
      else
        format.html { render :new }
        format.json { render json: @mail_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mail_boxes/1
  # PATCH/PUT /mail_boxes/1.json
  def update
    respond_to do |format|
      if @mail_box.update(mail_box_params)
        format.html { redirect_to @mail_box, notice: 'Mail box was successfully updated.' }
        format.json { render :show, status: :ok, location: @mail_box }
      else
        format.html { render :edit }
        format.json { render json: @mail_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mail_boxes/1
  # DELETE /mail_boxes/1.json
  def destroy
    @mail_box.destroy
    respond_to do |format|
      format.html { redirect_to mail_boxes_url, notice: 'Mail box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_mail_box
    @mail_box = MailBox.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def mail_box_params
    params.fetch(:mail_box, {})
  end
end

app/controllers/mail_boxes_controller.rb
class MailBoxesController < ApplicationController
  before_action :set_mail_box, only: [:show, :edit, :update, :destroy]

  # GET /mail_boxes
  # GET /mail_boxes.json
  def index
    @mail_boxes = MailBox.all
  end

  # GET /mail_boxes/1
  # GET /mail_boxes/1.json
  def show
    @messages = InboxMessage.joins(:mail_box).where(mail_boxes:  {id:params[:id]})
    @items = []
    begin
      @messages.each do | mm |
        @items << { message: mm.message}
      end
    rescue

    end
  end

  # GET /mail_boxes/new
  def new
    @mail_box = MailBox.new
  end

  # GET /mail_boxes/1/edit
  def edit
  end

  # POST /mail_boxes
  # POST /mail_boxes.json
  def create
    @mail_box = MailBox.new(mail_box_params)

    respond_to do |format|
      if @mail_box.save
        format.html { redirect_to @mail_box, notice: 'Mail box was successfully created.' }
        format.json { render :show, status: :created, location: @mail_box }
      else
        format.html { render :new }
        format.json { render json: @mail_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mail_boxes/1
  # PATCH/PUT /mail_boxes/1.json
  def update
    respond_to do |format|
      if @mail_box.update(mail_box_params)
        format.html { redirect_to @mail_box, notice: 'Mail box was successfully updated.' }
        format.json { render :show, status: :ok, location: @mail_box }
      else
        format.html { render :edit }
        format.json { render json: @mail_box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mail_boxes/1
  # DELETE /mail_boxes/1.json
  def destroy
    @mail_box.destroy
    respond_to do |format|
      format.html { redirect_to mail_boxes_url, notice: 'Mail box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mail_box
      @mail_box = MailBox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mail_box_params
      params.fetch(:mail_box, {})
    end
end

app/helpers/mail_boxes_helper.rb
module MailBoxesHelper
end

app/views/mail_boxes/_form.html.erb
<%= form_with(model: mail_box, local: true) do |form| %>
  <% if mail_box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mail_box.errors.count, "error") %> prohibited this mail_box from being saved:</h2>

      <ul>
        <% mail_box.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mail_boxes/edit.html.erb
<h1>Editing Mail Box</h1>

<%= render 'form', mail_box: @mail_box %>

<%= link_to 'Show', @mail_box %> |
<%= link_to 'Back', mail_boxes_path %>

app/views/mail_boxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mail Boxes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mail_boxes.each do |mail_box| %>
      <tr>
        <td><%= link_to 'Show', mail_box %></td>
        <td><%= link_to 'Edit', edit_mail_box_path(mail_box) %></td>
        <td><%= link_to 'Destroy', mail_box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mail Box', new_mail_box_path %>

app/views/mail_boxes/new.html.erb
<h1>New Mail Box</h1>

<%= render 'form', mail_box: @mail_box %>

<%= link_to 'Back', mail_boxes_path %>

app/views/mail_boxes/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-darkred">
  <tbody>
  <h1>Inbox </h1>
  <tr>
    <th scope="col"> messages</th>
  </tr>
  <tr>
    <% @items.each do |item|%>
    <tr>
      <td><%= item[:message] %></td>
      <td><%='answer'%></td>
    </tr>
  <% end %>
  </tr>
  </tbody>
</table>
<%= link_to 'Compose new message',new_user_mail_box_inbox_message_url(@mail_box,@mail_box.id)%>
<%#= link_to 'Compose new message',new_user_mail_box_inbox_message_url(@mail_box.id,@mail_box.id)%>