config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'search/search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  # get 'events/new_event_invitations', to: "event_invitations#new", as: :send_invite_otf

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        resources :mail_boxes do
          resources :inbox_messages
        end
        resources :subscriptions
      end
      resources :events do
        resources :comments
        resources :date_options do
          resources :vote_dates
        end
        resources :event_files
        resources :notifications
      end
      resources :event_invitations do
        resources :vote_dates
      end
      resources :comments
      resources :reports
      resources :organizations do
        resources :organization_files
        resources :subscriptions
      end
      resources :subscriptions
    end
  end


  resources :users, defaults: { format: :html } do
    resources :mail_boxes, defaults: { format: :html} do
      resources :inbox_messages, defaults: { format: :html}
    end
    resources :subscriptions, defaults: { format: :html }
  end
  resources :events, defaults: { format: :html } do
    resources :comments, defaults: { format: :html }
    resources :date_options, defaults: { format: :html } do
      resources :vote_dates, defaults: { format: :html }
    end
    resources :event_files, defaults: { format: :html }
    resources :notifications, defaults: { format: :html }
    resources :event_invitations, defaults: { format: :html}
  end

  resources :event_invitations, defaults: { format: :html} do
    resources :vote_dates, defaults: { format: :html }
  end
  resources :comments, defaults: { format: :html }
  resources :reports, defaults: { format: :html}
  resources :organizations, defaults: { format: :html } do
    resources :organization_files, defaults: { format: :html }
    resources :subscriptions, defaults: { format: :html }
  end
  resources :subscriptions, defaults: { format: :html }
  resources :inbox_messages, defaults: { format: :html}

end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users, :through => :subscriptions
  has_many :organization_files
  has_many :subscriptions
  has_many :events

  has_one_attached :photo
end

app/controllers/api/v1/organizations_controller.rb
class API::V1::OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @users = User.joins(:organizations).where(organizations: {id:params[:id]})
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_organization
    @organization = Organization.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def organization_params
    params.fetch(:organization, {})
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , :except => [:index,:show]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @users = User.joins(:organizations).where(organizations: {id:params[:id]})
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.fetch(:organization, {}).permit(:id,:name,:photo)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_with(model: @organization, local: true) do |form| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation ">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% organization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "flex-row col-auto table-darkred">
    <%= form.label :"Organization's Photo" %>
    <div class="form-group col-centered">
      <%= form.file_field :photo %>
    </div>
    <div class="form-group mt-2 ">
      <%= form.label :name %>
      <div class="form-group col-centered">
        <%= form.text_field :name, class: "table-gold" %>
      </div>
      <p>
        <%= form.submit submit_btn_text, class: ["btn","btn-red"] %>
        <%= link_to "Back", :back, class: ["btn", "btn-red"] %>
      </p>
    </div>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<br>
<%= render partial: "form",
           locals: {
               event: @organization,
               submit_btn_text: "Update"
           } %>
<%= link_to 'Show', @organization %>
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<br>

<%= link_to 'New Organization', new_organization_path %>
<tbody>
  <div class="row">
      <% @organizations.each do |organization| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm table-darkred">
          <p>
          <% if organization.photo.attached? %>
            <%= link_to image_tag(organization.photo,class: "card-img-top", width: "100%", background: "#55595c", color: "#eceeef"), url_for(organization) %>
          <%else %>
            <%= link_to image_tag("thumbnail.svg", class: "card-img-top", width: "100%", background: "#55595c", color: "#eceeef"), url_for(organization) %>
          <%end %>
          </p>
          <div class="card-body">
            <p class="card-text"><%= link_to organization.name, organization %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group  btn-group-toggle">
                <button type="button" class="btn btn-gold"><%= link_to "View", organization %></button>
                <% if user_signed_in? && current_user.administrator  %>
                  <button type="button" class="btn btn-sm btn-gold"><%= link_to "Edit", edit_organization_path(organization)%></button>
                  <button type="button" class="btn btn-sm btn-gold"><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></button>
                <%end %>
              </div>
              <!--
              <small class="text-muted">%= "#{(event.start_date.to_date - DateTime.now.to_date).to_i} days left!" %></small>
              -->
            </div>
          </div>
        </div>
      </div>
      <%end %>
  </div>
</tbody>

app/views/organizations/new.html.erb
<div class="row ml-0 mt-3">
  <h2>New Organization</h2>
</div>
<div class="row ml-0 mt-2">
  <p>Please enter the required information to create a new Organization:</p>
</div>
<%= render partial: "form",
           locals: {
               event: @organization,
               submit_btn_text: "Create"
           } %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="align-content-center">Organization: <%= @organization.name %></h1>

<br>
<% if @organization.photo.attached? %>
  <img class="img mx-auto d-block" data-toggle="modal" data-target="#exampleModalCenter"
  <%= image_tag @organization.photo,class: "image", width: "400", height: "auto", id:"img"  if @organization.photo.attached?%></img>
<%end %>

<table class="table table-darkred">
  <tbody>
  <th scope="col"> Members of <%=@organization.name %></th>
  <%@users.each do |v|%>
    <tr>
      <td><%= v.name%></td>
    </tr>
    </tbody>
  <%end %>
</table>

<table class="table-darkred">
  <td class="btn btn-group-toggle">
    <label class="btn table-gold">
      <%= link_to 'Edit Organization', edit_organization_path(@organization) %>
    </label>
    <label class="btn table-gold">
      <%= link_to 'Back', organizations_path %>
    </label>
  </td>
</table>
<%= link_to 'Become a Member' , new_organization_subscription_url(@organization) %>